a = input('Digite algo:')
print(f'O tipo primitivo desse valor é {type(a)}')
print(f'Só tem espaços? {a.isspace()}')
print(f'Só tem numeros? {a.isnumeric()}')
print(f'Só tem alfabeto? {a.isalpha()}')
print(f'Só tem letras maiusculas? {a.isupper()}')
print(f'É alfanumerico? {a.isalnum()}')
print(f'É minusculo? {a.islower()}')
print(f'É capitalizada? {a.istitle()}')